version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    volumes:
      - .:/app
    env_file: cmd/api/.env
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    entrypoint: sh -c "cd cmd/api/ && go run main.go"
    restart: always
    networks:
      - default

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    command:
      [
        "--sql_mode=",
        "--max_allowed_packet=64M",
        "--default-authentication-plugin=mysql_native_password",
      ]
    volumes:
      - db-data:/var/lib/mysql
      - "./database/initdb:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1"
      interval: 1s
      timeout: 10s
      retries: 5
    networks:
      - default

  redis:
    image: redis:6.2.7-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - default

networks:
  default:
    name: glossika

volumes:
  db-data:
